<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="8" passed="4" failed="1" skipped="3">
  <reporter-output>
  </reporter-output>
  <suite started-at="2019-06-04T19:25:58Z" name="Default suite" finished-at="2019-06-04T19:25:58Z" duration-ms="45">
    <groups>
    </groups>
    <test started-at="2019-06-04T19:25:58Z" name="Default test" finished-at="2019-06-04T19:25:58Z" duration-ms="45">
      <class name="testNGGroupID.testNG.RegistrationTest">
        <test-method is-config="true" signature="beforeSuite()[pri:0, instance:testNGGroupID.testNG.RegistrationTest@6f3b5d16]" started-at="2019-06-04T19:25:58Z" name="beforeSuite" finished-at="2019-06-04T19:25:58Z" duration-ms="8" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeSuite -->
        <test-method signature="emailTest2()[pri:1, instance:testNGGroupID.testNG.RegistrationTest@6f3b5d16]" started-at="2019-06-04T19:25:58Z" name="emailTest2" finished-at="2019-06-04T19:25:58Z" duration-ms="9" status="FAIL">
          <exception class="junit.framework.ComparisonFailure">
            <message>
              <![CDATA[expected:<Babek> but was:<John>]]>
            </message>
            <full-stacktrace>
              <![CDATA[junit.framework.ComparisonFailure: expected:<Babek> but was:<John>
at junit.framework.Assert.assertEquals(Assert.java:81)
at junit.framework.Assert.assertEquals(Assert.java:87)
at testNGGroupID.testNG.RegistrationTest.emailTest2(RegistrationTest.java:33)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.ComparisonFailure -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- emailTest2 -->
        <test-method signature="phoneTest4()[pri:1, instance:testNGGroupID.testNG.RegistrationTest@6f3b5d16]" started-at="2019-06-04T19:25:58Z" name="phoneTest4" finished-at="2019-06-04T19:25:58Z" depends-on-methods="testNGGroupID.testNG.RegistrationTest.emailTest2" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method RegistrationTest.phoneTest4()[pri:1, instance:testNGGroupID.testNG.RegistrationTest@6f3b5d16] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method RegistrationTest.phoneTest4()[pri:1, instance:testNGGroupID.testNG.RegistrationTest@6f3b5d16] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:888)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- phoneTest4 -->
        <test-method signature="emailTest3()[pri:2, instance:testNGGroupID.testNG.RegistrationTest@6f3b5d16]" started-at="2019-06-04T19:25:58Z" name="emailTest3" finished-at="2019-06-04T19:25:58Z" depends-on-methods="testNGGroupID.testNG.RegistrationTest.emailTest2" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method RegistrationTest.emailTest3()[pri:2, instance:testNGGroupID.testNG.RegistrationTest@6f3b5d16] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method RegistrationTest.emailTest3()[pri:2, instance:testNGGroupID.testNG.RegistrationTest@6f3b5d16] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:888)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- emailTest3 -->
        <test-method signature="phoneTest3()[pri:2, instance:testNGGroupID.testNG.RegistrationTest@6f3b5d16]" started-at="2019-06-04T19:25:58Z" name="phoneTest3" finished-at="2019-06-04T19:25:58Z" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- phoneTest3 -->
        <test-method signature="emailTest4()[pri:2, instance:testNGGroupID.testNG.RegistrationTest@6f3b5d16]" started-at="2019-06-04T19:25:58Z" name="emailTest4" finished-at="2019-06-04T19:25:58Z" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- emailTest4 -->
        <test-method signature="phoneTest1()[pri:3, instance:testNGGroupID.testNG.RegistrationTest@6f3b5d16]" started-at="2019-06-04T19:25:58Z" name="phoneTest1" finished-at="2019-06-04T19:25:58Z" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- phoneTest1 -->
        <test-method signature="emailTest1()[pri:4, instance:testNGGroupID.testNG.RegistrationTest@6f3b5d16]" started-at="2019-06-04T19:25:58Z" name="emailTest1" finished-at="2019-06-04T19:25:58Z" depends-on-methods="testNGGroupID.testNG.RegistrationTest.emailTest2" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method RegistrationTest.emailTest1()[pri:4, instance:testNGGroupID.testNG.RegistrationTest@6f3b5d16] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method RegistrationTest.emailTest1()[pri:4, instance:testNGGroupID.testNG.RegistrationTest@6f3b5d16] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:888)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- emailTest1 -->
        <test-method signature="phoneTest2()[pri:4, instance:testNGGroupID.testNG.RegistrationTest@6f3b5d16]" started-at="2019-06-04T19:25:58Z" name="phoneTest2" finished-at="2019-06-04T19:25:58Z" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- phoneTest2 -->
        <test-method is-config="true" signature="afterSuite()[pri:0, instance:testNGGroupID.testNG.RegistrationTest@6f3b5d16]" started-at="2019-06-04T19:25:58Z" name="afterSuite" finished-at="2019-06-04T19:25:58Z" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuite -->
      </class> <!-- testNGGroupID.testNG.RegistrationTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
