<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-7AO4KKL" failures="1" tests="8" name="Default test" time="0.045" errors="0" timestamp="04 Jun 2019 19:25:58 GMT">
  <testcase classname="testNGGroupID.testNG.RegistrationTest" name="emailTest2" time="0.009">
    <failure type="junit.framework.ComparisonFailure" message="expected:&amp;lt;Babek&amp;gt; but was:&amp;lt;John&amp;gt;">
      <![CDATA[junit.framework.ComparisonFailure: expected:<Babek> but was:<John>
at junit.framework.Assert.assertEquals(Assert.java:81)
at junit.framework.Assert.assertEquals(Assert.java:87)
at testNGGroupID.testNG.RegistrationTest.emailTest2(RegistrationTest.java:33)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- emailTest2 -->
  <testcase classname="testNGGroupID.testNG.RegistrationTest" name="phoneTest4" time="0.0">
    <skipped/>
  </testcase> <!-- phoneTest4 -->
  <testcase classname="testNGGroupID.testNG.RegistrationTest" name="emailTest3" time="0.0">
    <skipped/>
  </testcase> <!-- emailTest3 -->
  <testcase classname="testNGGroupID.testNG.RegistrationTest" name="phoneTest3" time="0.001"/>
  <testcase classname="testNGGroupID.testNG.RegistrationTest" name="emailTest4" time="0.002"/>
  <testcase classname="testNGGroupID.testNG.RegistrationTest" name="phoneTest1" time="0.001"/>
  <testcase classname="testNGGroupID.testNG.RegistrationTest" name="emailTest1" time="0.0">
    <skipped/>
  </testcase> <!-- emailTest1 -->
  <testcase classname="testNGGroupID.testNG.RegistrationTest" name="phoneTest2" time="0.001"/>
</testsuite> <!-- Default test -->
