<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="3" hostname="Babek-Chalabi" name="testNGGroupID.testNG.RegistrationTest" tests="8" failures="0" timestamp="24 Jan 2019 19:35:54 GMT" time="0.010" errors="1">
  <testcase name="phoneTest4" time="0.000" classname="testNGGroupID.testNG.RegistrationTest">
    <skipped/>
  </testcase> <!-- phoneTest4 -->
  <testcase name="emailTest2" time="0.007" classname="testNGGroupID.testNG.RegistrationTest">
    <error type="junit.framework.ComparisonFailure" message="expected:&lt;Babek&gt; but was:&lt;John&gt;">
      <![CDATA[junit.framework.ComparisonFailure: expected:<Babek> but was:<John>
at junit.framework.Assert.assertEquals(Assert.java:81)
at junit.framework.Assert.assertEquals(Assert.java:87)
at testNGGroupID.testNG.RegistrationTest.emailTest2(RegistrationTest.java:33)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- emailTest2 -->
  <testcase name="emailTest3" time="0.000" classname="testNGGroupID.testNG.RegistrationTest">
    <skipped/>
  </testcase> <!-- emailTest3 -->
  <testcase name="phoneTest3" time="0.001" classname="testNGGroupID.testNG.RegistrationTest"/>
  <testcase name="emailTest4" time="0.000" classname="testNGGroupID.testNG.RegistrationTest"/>
  <testcase name="phoneTest1" time="0.001" classname="testNGGroupID.testNG.RegistrationTest"/>
  <testcase name="phoneTest2" time="0.001" classname="testNGGroupID.testNG.RegistrationTest"/>
  <testcase name="emailTest1" time="0.000" classname="testNGGroupID.testNG.RegistrationTest">
    <skipped/>
  </testcase> <!-- emailTest1 -->
</testsuite> <!-- testNGGroupID.testNG.RegistrationTest -->
